---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "[dependabot] "
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: cargo
    directories:
      - /
      - /bench
      - /fuzz
    schedule:
      interval: weekly
    commit-message:
      prefix: "[dependabot] "
    groups:
      cargo:
        patterns:
          - "*"
