[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all-features"]

[tasks.doc]
env = { "RUSTDOCFLAGS" = "--cfg docsrs" }
toolchain = "nightly"
command = "cargo"
args = ["doc", "-p", "rsdns", "--all-features", "--no-deps", "--open"]
workspace = false

[tasks.fmt]
command = "cargo"
args = ["fmt", "--all", "--", "--check"]
