[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all-features"]
workspace = false

[tasks.doc]
env = { "RUSTDOCFLAGS" = "--cfg docsrs" }
toolchain = "nightly"
command = "cargo"
args = ["doc", "--all-features", "--no-deps", "--open"]
workspace = false
