name: ci

on:
  push:
  pull_request:
  schedule:
    - cron: '0 1 * * 0'

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ${{ matrix.runs_on }}
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.51.0  # MSRV
        runs_on:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        name: Build
        with:
          command: build
          args: --all-features

      - uses: actions-rs/cargo@v1
        name: Test
        with:
          command: test
          args: --all-features

      - uses: actions-rs/cargo@v1
        name: Format
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        name: Lint
        with:
          command: clippy
          args: --all-features -- -D warnings

  doc-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        name: Doc
        env:
          RUSTDOCFLAGS: "--cfg docsrs"
        with:
          command: doc
          args: --all-features --no-deps
