name: ci

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ${{ matrix.runs_on }}
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.45.0  # minimal supported version
        runs_on:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        name: Build
        with:
          command: build
          args: --all-features

      - uses: actions-rs/cargo@v1
        name: Test
        with:
          command: test
          args: --all-features

      - uses: actions-rs/cargo@v1
        name: Format
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        name: Lint
        if: ${{ matrix.rust == 'stable' || matrix.rust == '1.45.0' }}
        with:
          command: clippy
          args: --all-features -- -D warnings

      - uses: actions-rs/cargo@v1
        name: Lint
        if: ${{ matrix.rust != 'stable' && matrix.rust != '1.45.0' }}
        with:
          command: clippy
          args: --all-features -- -D warnings -A clippy::upper_case_acronyms

  doc-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        name: Doc
        env:
          RUSTDOCFLAGS: "--cfg docsrs"
        with:
          command: doc
          args: --all-features --no-deps
