name: ci

on:
  push:
  pull_request:
  schedule:
    - cron: '0 1 * * 0'

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ${{ matrix.runs_on }}
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.51.0  # MSRV
        runs_on:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        feature:
          - net-std
          - net-async-std
          - net-tokio
          - net-smol
          - all
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        name: build rsdns
        if: ${{ matrix.feature != 'all' }}
        with:
          command: build
          args: -p rsdns --no-default-features --features ${{ matrix.feature }}

      - uses: actions-rs/cargo@v1
        name: build all rsdns
        if: ${{ matrix.feature == 'all' }}
        with:
          command: build
          args: -p rsdns --all-features

      - uses: actions-rs/cargo@v1
        name: test rsdns
        if: ${{ matrix.feature != 'all' }}
        with:
          command: test
          args: -p rsdns --no-default-features --features ${{ matrix.feature }}

      - uses: actions-rs/cargo@v1
        name: test all rsdns
        if: ${{ matrix.feature == 'all' }}
        with:
          command: test
          args: -p rsdns --all-features

      - uses: actions-rs/cargo@v1
        name: lint rsdns
        if: ${{ matrix.feature != 'all' }}
        with:
          command: clippy
          args: -p rsdns --no-default-features --features ${{ matrix.feature }} -- -D warnings

      - uses: actions-rs/cargo@v1
        name: lint all rsdns
        if: ${{ matrix.feature == 'all' }}
        with:
          command: clippy
          args: -p rsdns --all-features -- -D warnings

  common-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        name: format all
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        name: doc rsdns
        env:
          RUSTDOCFLAGS: "--cfg docsrs"
        with:
          command: doc
          args: -p rsdns --all-features --no-deps
