name: fuzz

on:
  push:
    branches:
      - '**-fuzz'
  schedule:
    - cron: '0 1,18 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: nightly
          override: true

      - uses: actions-rs/cargo@v1
        name: install cargo-fuzz
        with:
          command: install
          args: cargo-fuzz

      - uses: actions-rs/cargo@v1
        name: fuzz rrset_from_msg
        with:
          command: fuzz
          args: run rrset_from_msg -- -max_total_time=7200 -jobs=2 -workers=2 -verbosity=0
