name: fuzz

on:
  push:
    branches:
      - '**-fuzz'
  schedule:
    - cron: '0 1,18 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly

      - name: install cargo-fuzz
        run: cargo install cargo-fuzz

      - name: fuzz rrset_from_msg
        run: cargo fuzz run rrset_from_msg -- -max_total_time=7200 -jobs=2 -workers=2 -verbosity=0
